# Base Docker Compose configuration for CME Development
# Shared networks, volumes, and base configurations

# =================================================================
# NETWORKS
# =================================================================
networks:
  external:
    external: true
    name: external
  cme-dev:
    external: false
    name: cme-dev
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
  cme-monitoring:
    external: false
    name: cme-monitoring
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16

# =================================================================
# VOLUMES
# =================================================================
volumes:
  # WordPress
  wordpress-data:
    driver: local
  wordpress-logs:
    driver: local
  wordpress-cache:
    driver: local

  # Matomo
  matomo-data:
    driver: local
  matomo-logs:
    driver: local

  # n8n
  n8n-data:
    driver: local
  n8n-logs:
    driver: local

  # GlitchTip
  glitchtip-uploads:
    driver: local

  # GitLab
  gitlab-config:
    driver: local
  gitlab-logs:
    driver: local
  gitlab-data:
    driver: local

  # Monitoring
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  loki-data:
    driver: local
  alertmanager-data:
    driver: local

# =================================================================
# COMMON SERVICE CONFIGURATIONS
# =================================================================

# Restart policy for all services
x-restart-policy: &restart-policy
  restart: unless-stopped

# Default logging configuration
x-logging: &default-logging
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

# Default health check settings
x-healthcheck-defaults: &healthcheck-defaults
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 60s

# Common labels for service identification
x-dev-labels: &dev-labels
  labels:
    - "com.cme.project=cme-stack"
    - "com.cme.environment=development"
    - "com.cme.stack-version=0.2.0"

# Security defaults for development
x-security-opts: &security-opts
  security_opt:
    - no-new-privileges:true

# Common tmpfs mounts for logs
x-log-tmpfs: &log-tmpfs
  tmpfs:
    - /tmp
    - /var/log
