# File: monitoring/promtail/promtail-config.yml
# Promtail configuration for CME Stack development environment

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://dev-loki:3100/loki/api/v1/push

scrape_configs:
  # Docker container logs
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs:
      - json:
          expressions:
            tag:
          source: attrs
      - regex:
          expression: (?P<container_name>(?:[^|])*[^|])
          source: tag
      - timestamp:
          format: RFC3339Nano
          source: time
      - labels:
          stream:
          container_name:
      - output:
          source: output

  # WordPress logs
  - job_name: wordpress
    static_configs:
      - targets:
          - localhost
        labels:
          job: wordpress
          service: wordpress
          __path__: /var/log/wordpress/*.log

  # Matomo logs  
  - job_name: matomo
    static_configs:
      - targets:
          - localhost
        labels:
          job: matomo
          service: matomo
          __path__: /var/www/html/tmp/logs/*.log

  # n8n logs
  - job_name: n8n
    static_configs:
      - targets:
          - localhost
        labels:
          job: n8n
          service: n8n
          __path__: /var/log/n8n/*.log

  # GitLab logs
  - job_name: gitlab
    static_configs:
      - targets:
          - localhost
        labels:
          job: gitlab
          service: gitlab
          __path__: /var/log/gitlab/**/*.log
