global:
  smtp_smarthost: "dev-mailhog:1025"
  smtp_from: "alerts@cruisemadeeasy.dev"
  smtp_require_tls: false

route:
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: "web.hook"
  routes:
    - match:
        severity: critical
      receiver: "critical-alerts"
    - match:
        severity: warning
      receiver: "warning-alerts"

receivers:
  - name: "web.hook"
    webhook_configs:
      - url: "http://dev-glitchtip-web:8000/api/0/webhook/alertmanager/"
        send_resolved: true

  - name: "critical-alerts"
    email_configs:
      - to: "admin@cruisemadeeasy.dev"
        subject: "[CRITICAL] CME Dev Alert: {{ .GroupLabels.alertname }}"
        body: |
          Alert: {{ .GroupLabels.alertname }}

          {{ range .Alerts }}
          Summary: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}

          Labels:
          {{ range .Labels.SortedPairs }}  {{ .Name }}: {{ .Value }}
          {{ end }}
          {{ end }}
        html: |
          <h2>Critical Alert: {{ .GroupLabels.alertname }}</h2>
          {{ range .Alerts }}
          <h3>{{ .Annotations.summary }}</h3>
          <p>{{ .Annotations.description }}</p>
          <p><strong>Labels:</strong></p>
          <ul>
          {{ range .Labels.SortedPairs }}
          <li>{{ .Name }}: {{ .Value }}</li>
          {{ end }}
          </ul>
          {{ end }}

  - name: "warning-alerts"
    email_configs:
      - to: "dev-team@cruisemadeeasy.dev"
        subject: "[WARNING] CME Dev Alert: {{ .GroupLabels.alertname }}"
        body: |
          Warning Alert: {{ .GroupLabels.alertname }}

          {{ range .Alerts }}
          Summary: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          {{ end }}

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "dev", "instance"]
