# File: monitoring/alertmanager/alertmanager.yml
# AlertManager configuration for CME Stack development environment

global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@cruisemadeeasy.dev'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'

receivers:
  - name: 'web.hook'
    email_configs:
      - to: 'admin@cruisemadeeasy.dev'
        subject: 'CME Stack Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
